name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_MODULES_CACHE_VERSION: v0.1

jobs:
  install: 
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}/BuildAndCheck/${{ github.ref }}/${{ github.head_ref }}/${{ github.base_ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8'

      - name: Store node-modules Cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ env.NODE_MODULES_CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node-modules
        run: |
          yarn install

  build:
    needs: [install]
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}/BuildAndCheck/${{ github.ref }}/${{ github.head_ref }}/${{ github.base_ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8'

      - name: Restore node-modules Cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ env.NODE_MODULES_CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Store build Cache
        uses: actions/cache@v2
        id: build-cache
        with:
          path: build
          key: ${{ runner.os }}-build-${{ env.NODE_MODULES_CACHE_VERSION }}-${{ github.sha }}

      - name: Build
        run: yarn build

  test-lint-typecheck-e2e:
    needs: [build]
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}/BuildAndCheck/${{ github.ref }}/${{ github.head_ref }}/${{ github.base_ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8'

      - name: Restore node-modules Cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ env.NODE_MODULES_CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Restore build Cache
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-${{ env.NODE_MODULES_CACHE_VERSION }}-${{ github.sha }}

      - run: yarn test
      - run: yarn lint
      - run: yarn typecheck
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          # the entire command will automatically be prefixed with "npm"
          # and we need the second "npm" to execute "cypress run ..." command line
          command-prefix: 'percy exec -- npx'
